In [2]:
import numpy as np
import random
import time

## numpy和list的性能比较

In [13]:
a = []
for i in range(1000000):
    a.append(random.random())

In [14]:
# 使用list
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
# 使用numpy
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

0.005019426345825195 0.003995418548583984


## 创建一维数组

In [18]:
# 1. 直接传入列表的方式
t1 = np.array([random.randint(1,30) for x in range(10)])
print(t1)
print(type(t1))

# 2. 传入range生成序列
t2 = np.array(range(10))
print(t2)
print(type(t2))

# 3. 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[ 4 12 20 15  2 14  6 19 25 15]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


## 创建二维数组

In [19]:
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# 数组的属性
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)
# 形状（行，列）
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


## 调整数组形状

In [25]:
four = np.array([[1,2,3],[4,5,6]])
# 修改的是原有的
four.shape = (3,2)
#print(four)
# 返回一个新的数组，不改变原有的，id不同
four = four.reshape(3,2)
#print(four)

# 将多维变成一维数组
five = four.reshape((6,),order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
# six = four.flatten(order='F') # 以列为主的顺序展开
print(five)

# 拓展：数组的形状
t = np.arange(24)
print(t)
print(t.shape)
# 转换成二维
t1 = t.reshape((4,6))
print(t1)
print(t1.shape)

[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [ ]:
# 将数组转成list
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist()

In [26]:
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2)) # round()函数 保留小数点后两位
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.69
[0.27 0.52 0.31 0.82 0.38 0.68 0.85 0.44 0.4  0.58]


In [27]:
## 数组的计算

In [33]:
n = np.array([random.randint(1,10) for i in range(10)])
n.shape=(2,5)
print(n)
print(n+2)
print("-"*20)
print(n*2)
print("-"*20)
print(n/2)

[[ 2  6  3  5  9]
 [10  8  1  8  5]]
[[ 4  8  5  7 11]
 [12 10  3 10  7]]
--------------------
[[ 4 12  6 10 18]
 [20 16  2 16 10]]
--------------------
[[1.  3.  1.5 2.5 4.5]
 [5.  4.  0.5 4.  2.5]]


In [34]:
# 同种形状的数组(对应位置进行计算操作)
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1+t2)
print(t1*t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [35]:
# 不种形状的多维数组不能计算
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(18).reshape((3,6))
print(t1)
print(t2)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

In [36]:
#行数或者列数相同的一维数组和多维数组可以进行计算：
#行形状相同（会与每一行数组的对应位相操作)
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1-t2)

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [37]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


## 数组的索引和切片

In [38]:
a = np.arange(10)#冒号分割切片参数来进行切片操作 start:stop:step   print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)
# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [39]:
# 多维数组的索引和切片
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


## 数组的修改

In [41]:
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
#
# # 修改某一列的值
t[:, 1] = 0

# # 修改连续多行
t[1:3, :] = 0
#
# # 修改连续多列
t[:, 1:4] = 0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0
# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0 # 与
t[(t < 2) | (t > 6)] = 0 # 或
t[~(t > 6)] = 0 # 非
# print(t)
t=t.clip(10,18)
print(t)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [40]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[False  True]
 [ True  True]
 [False  True]]
